name: dart_utils
description: A simple command-line application.
version: 1.0.0
repository: https://github.com/shizoe/PLP_Dart_DART_FLUTTER/PLP_Dart_CLI/dart_datatypes

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
